<a href="https://colab.research.google.com/github/saudjabarali/pandas_grind/blob/main/PandasPractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🐼 PANDAS START (Structured + Practical)

We’ll do:

Core concepts
Practice tasks
Real-world thinking
🔹 What is Pandas?
🗣️

“Pandas is a Python library used for data manipulation and analysis using DataFrames and Series.”

🧠 Core Concepts
Concept	Meaning
Series	1D labeled array
DataFrame	2D table (rows + columns)
Index	Row labels
Columns	Features
🧪 PANDAS PRACTICE SET (PD1–PD20)
🟢 LEVEL 1 – Basics

PD1

Create a Series from:

[10, 20, 30, 40]

PD2

Create a DataFrame:

Name   Age
Saud   20
Ayaan  21
Aisha  19

PD3

Read a CSV file


PD4

Display:

First 5 rows
Last 5 rows
PD5

Get:

Column names
Data types

🟡 LEVEL 2 – Selection & Filtering

PD6

Select only Name column


PD7

Filter rows where Age > 20


PD8

Select multiple columns


PD9

Add a new column Salary


PD10

Drop a column


🔵 LEVEL 3 – Operations

PD11

Find:

Mean
Max
Min

PD12

Sort DataFrame by Age


PD13

Handle missing values


PD14

Rename columns


PD15

Apply function on column


🔴 LEVEL 4 – Advanced
PD16

Group by Age and count


PD17

Merge two DataFrames


PD18

Find duplicates


PD19

Pivot table


PD20

Value counts

In [ ]:
import pandas as pd

In [ ]:
#PD1 Create a Series from: [10, 20, 30, 40]
srs=pd.Series([10,20,30,40])
print(srs)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
#PD2 Create a DataFrame: Name Age Saud 20 Ayaan 21 Aisha 19
data= {
    "Name": ["Saud","Ayaan","Aisha"],
    "Age": [20,21,19]
}
df=pd.DataFrame(data)
print(df)

    Name  Age
0   Saud   20
1  Ayaan   21
2  Aisha   19

In [ ]:
#PD3-Read a CSV file
df=pd.read_csv("/content/steam_top_games_2026.csv")
df.head()

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
0,794260,Outward Definitive Edition,"May 17, 2022",False,4.79,False,88,Nine Dots Studio,"Prime Matter, Deep Silver",RPG,...,"1,000,000 .. 2,000,000",1332,824,465,469,0,1,72,No remarkable journey is achieved without grea...,https://shared.akamai.steamstatic.com/store_it...
1,253920,Gorky 17,"Sep 27, 2013",False,9.99,False,0,Metropolis Software,TopWare Interactive,"RPG, Strategy",...,"200,000 .. 500,000",301,0,328,61,17,2,0,November 2008. NATO intelligence services repo...,https://shared.akamai.steamstatic.com/store_it...
2,613010,Secret in Story,"Jun 19, 2017",False,0.89,False,10,Naivus Luo,Naivus Luo,"Adventure, Indie",...,"2,000,000 .. 5,000,000",251,0,243,0,0,0,32,"Accompanied by beautiful piano music, you begi...",https://shared.akamai.steamstatic.com/store_it...
3,892420,懒人修仙传,"Nov 14, 2018",False,3.99,False,0,托更的修罗,托更的修罗,"Casual, Indie, RPG, Simulation",...,"200,000 .. 500,000",5786,0,9223,41,0,0,0,这是一款很&quot;休闲&quot;的文字挂机游戏，游戏小而系统完善，玩法丰富，极其耗电，...,https://shared.akamai.steamstatic.com/store_it...
4,914010,Train Station Renovation,"Oct 1, 2020",False,18.99,False,0,Live Motion Games,"Live Motion Games, Frozen Way, PlayWay S.A., F...","Casual, Indie, Simulation",...,"200,000 .. 500,000",448,0,201,16,0,1,73,"Welcome to an old, ruined train station. A pla...",https://shared.akamai.steamstatic.com/store_it...

In [ ]:
#PD4 Display: First 5 rows Last 5 rows
df.tail()

,app_id,name,release_date,coming_soon,price_usd,is_free,discount_pct,developer,publisher,genres,...,estimated_owners,avg_playtime_forever,avg_playtime_2weeks,median_playtime,peak_ccu,required_age,dlc_count,achievements,short_description,header_image
1490,1590910,Forgive Me Father,"Apr 7, 2022",False,19.99,False,0,Byte Barrel,Fulqrum Publishing,"Action, Indie",...,"500,000 .. 1,000,000",204,0,106,61,0,1,20,Forgive Me Father is a dark retro horror FPS s...,https://shared.akamai.steamstatic.com/store_it...
1491,1693970,PARTY RUSH!!,"Mar 23, 2022",False,9.99,False,0,SECHAN,HIKE Inc.,"Adventure, Casual, Indie, RPG",...,"200,000 .. 500,000",0,0,0,0,0,1,15,"Here we present, a cynical RPG with close to 1...",https://shared.akamai.steamstatic.com/store_it...
1492,1225330,NBA 2K21,"Sep 4, 2020",False,0.00,False,0,Visual Concepts,2K,"Simulation, Sports",...,"1,000,000 .. 2,000,000",6563,0,4090,148,0,0,50,NOTE: All multiplayer servers for NBA 2K21 wil...,https://shared.akamai.steamstatic.com/store_it...
1493,764030,Realm Revolutions,"Jan 5, 2018",False,0.00,True,0,Aleksandr Golovkin,Aleksandr Golovkin,Free To Play,...,"200,000 .. 500,000",20080,0,4114,57,0,0,0,Earning coins and resources is more fun than e...,https://shared.akamai.steamstatic.com/store_it...
1494,444200,World of Tanks Blitz,"Nov 9, 2016",False,0.00,True,0,Wargaming Group Limited,Wargaming Group Limited,"Action, Massively Multiplayer, Simulation, Str...",...,"10,000,000 .. 20,000,000",9782,254,180,5707,0,15,0,Blow off steam and tank turrets in a free-to-p...,https://shared.akamai.steamstatic.com/store_it...

In [ ]:
#PD5 Get:Column names Data types
print(df.columns)
df.dtypes

Index(['app_id', 'name', 'release_date', 'coming_soon', 'price_usd', 'is_free',
       'discount_pct', 'developer', 'publisher', 'genres', 'categories',
       'tags', 'platforms_win', 'platforms_mac', 'platforms_linux',
       'metacritic_score', 'recommendations', 'positive_reviews',
       'negative_reviews', 'estimated_owners', 'avg_playtime_forever',
       'avg_playtime_2weeks', 'median_playtime', 'peak_ccu', 'required_age',
       'dlc_count', 'achievements', 'short_description', 'header_image'],
      dtype='object')

app_id                    int64
name                     object
release_date             object
coming_soon                bool
price_usd               float64
is_free                    bool
discount_pct              int64
developer                object
publisher                object
genres                   object
categories               object
tags                     object
platforms_win              bool
platforms_mac              bool
platforms_linux            bool
metacritic_score        float64
recommendations           int64
positive_reviews          int64
negative_reviews          int64
estimated_owners         object
avg_playtime_forever      int64
avg_playtime_2weeks       int64
median_playtime           int64
peak_ccu                  int64
required_age              int64
dlc_count                 int64
achievements              int64
short_description        object
header_image             object
dtype: object

In [ ]:
df=pd.read_csv("/content/pandas_practice.csv")

In [ ]:
df.head()

    Name  Age    Department  Salary       City  Experience
0   Saud   20  Data Science   30000    Chennai           1
1  Ayaan   21            AI   40000  Bangalore           2
2  Aisha   19            HR   25000  Hyderabad           1
3  Rahul   25       Finance   50000     Mumbai           3
4   Neha   22  Data Science   45000      Delhi           2

In [ ]:
df.tail()

      Name  Age    Department  Salary       City  Experience
7    Arjun   26       Finance   52000  Hyderabad           4
8   Ritika   21  Data Science   42000     Mumbai           2
9   Farhan   28            AI   60000      Delhi           5
10   Kiran   27            HR   38000    Chennai           4
11   Meena   29       Finance   65000  Bangalore           5

In [ ]:
df.dtypes

Name          object
Age            int64
Department    object
Salary         int64
City          object
Experience     int64
dtype: object

In [ ]:
#PD6 Select only Name column
df["Name"]

0       Saud
1      Ayaan
2      Aisha
3      Rahul
4       Neha
5      Imran
6       Zara
7      Arjun
8     Ritika
9     Farhan
10     Kiran
11     Meena
Name: Name, dtype: object

In [ ]:
#PD7 Filter rows where Age > 20
df[df["Age"]>20]

      Name  Age    Department  Salary       City  Experience
1    Ayaan   21            AI   40000  Bangalore           2
3    Rahul   25       Finance   50000     Mumbai           3
4     Neha   22  Data Science   45000      Delhi           2
5    Imran   24            AI   48000    Chennai           3
6     Zara   23            HR   35000  Bangalore           2
7    Arjun   26       Finance   52000  Hyderabad           4
8   Ritika   21  Data Science   42000     Mumbai           2
9   Farhan   28            AI   60000      Delhi           5
10   Kiran   27            HR   38000    Chennai           4
11   Meena   29       Finance   65000  Bangalore           5

In [ ]:
#PD8cSelect multiple columns
df[["Age","Name"]]

    Age    Name
0    20    Saud
1    21   Ayaan
2    19   Aisha
3    25   Rahul
4    22    Neha
5    24   Imran
6    23    Zara
7    26   Arjun
8    21  Ritika
9    28  Farhan
10   27   Kiran
11   29   Meena

In [45]:
import numpy as np

In [46]:
#PD9-Add a new column Salary
df["Salary"]=[500000,400000,10000,40000,np.nan,30000,100000,67000,69000,30000,70000,50000]
df.head(12)

      Name  Age    Department    Salary       City  Experience
0     Saud   20  Data Science  500000.0    Chennai           1
1    Ayaan   21            AI  400000.0  Bangalore           2
2    Aisha   19            HR   10000.0  Hyderabad           1
3    Rahul   25       Finance   40000.0     Mumbai           3
4     Neha   22  Data Science       NaN      Delhi           2
5    Imran   24            AI   30000.0    Chennai           3
6     Zara   23            HR  100000.0  Bangalore           2
7    Arjun   26       Finance   67000.0  Hyderabad           4
8   Ritika   21  Data Science   69000.0     Mumbai           2
9   Farhan   28            AI   30000.0      Delhi           5
10   Kiran   27            HR   70000.0    Chennai           4
11   Meena   29       Finance   50000.0  Bangalore           5

In [50]:
#PD10-Drop a column
df=df.drop("City", axis=1)

In [51]:
df.head()

    Name  Age    Department    Salary  Experience
0   Saud   20  Data Science  500000.0           1
1  Ayaan   21            AI  400000.0           2
2  Aisha   19            HR   10000.0           1
3  Rahul   25       Finance   40000.0           3
4   Neha   22  Data Science       NaN           2

In [58]:
#PD11 Find:Mean Max Min
print(df["Salary"].mean())
print(df["Salary"].max())
print(df["Salary"].min())

124181.81818181818
500000.0
10000.0